services:
    api:
        build:
            context: ../..
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            EXAMPLE_MODULE: "examples.auth_envvar:app"
            LOG_FORMAT: json
            LOG_LEVEL: INFO
        restart: unless-stopped
        networks:
            - servicekit-auth

networks:
    servicekit-auth:
        driver: bridge
