services:
    api:
        build:
            context: ../..
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            EXAMPLE_MODULE: "examples.auth_docker_secrets:app"
            SERVICEKIT_API_KEY_FILE: "/run/secrets/api_keys"
            LOG_FORMAT: json
            LOG_LEVEL: INFO
        volumes:
            - ./secrets/api_keys.txt:/run/secrets/api_keys:ro
        restart: unless-stopped
        networks:
            - servicekit-auth

networks:
    servicekit-auth:
        driver: bridge
