[project]
name = "servicekit-demo-auth_basic"
version = "0.1.0"
description = "auth basic demo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "servicekit",
]

[tool.uv.sources]
servicekit = { path = "../..", editable = true }
