[project]
name = "servicekit-demo-auth_envvar"
version = "0.1.0"
description = "auth envvar demo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "servicekit",
]

[tool.uv.sources]
servicekit = { path = "../..", editable = true }
