coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default

ignore:
  - "examples/**"
  - "tests/**"
  - "docs/**"
