services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            EXAMPLE_MODULE: "examples.core_api:app"
            LOG_FORMAT: json
            LOG_LEVEL: INFO

        restart: unless-stopped

        networks:
            - servicekit

networks:
    servicekit:
        driver: bridge
