apiVersion: 1

datasources:
    # --- Primary Prometheus data source ---
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      uid: prometheus
      url: http://prometheus:9090
      isDefault: true
      editable: false
      basicAuth: false
      jsonData:
          timeInterval: "15s"
          httpMethod: GET

    # --- Built-in Grafana test data generator ---
    - name: TestData DB
      type: testdata
      access: proxy
      orgId: 1
      uid: testdata
      isDefault: false
      editable: true
