[project]
name = "servicekit-demo-app-hosting"
version = "0.1.0"
description = "App hosting demo showcasing static web app mounting"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "servicekit",
]

[tool.uv.sources]
servicekit = { path = "../..", editable = true }
