[project]
name = "servicekit-demo-job_scheduler"
version = "0.1.0"
description = "job scheduler demo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "servicekit",
]

[tool.uv.sources]
servicekit = { path = "../..", editable = true }
